sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kalpeshkhune/react-test -f ./client/Dockerfile.dev ./client  

script:
  - docker run -e CI=true kalpeshkhune/react-test npm test
  
after_success:
  - docker build -t kalpeshkhune/multi-client ./client
  - docker build -t kalpeshkhune/multi-nginx ./nginx
  - docker build -t kalpeshkhune/multi-server ./server
  - docker build -t kalpeshkhune/multi-worker ./worker
 #Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Take those images and push them to docker hub
  - docker push kalpeshkhune/multi-client
  - docker push kalpeshkhune/multi-nginx
  - docker push kalpeshkhune/multi-server
  - docker push kalpeshkhune/multi-worker
 
deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-505294226570
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  



 
